name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
    label:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign Integration issues to project
      if: |
        contains(github.event.issue.labels.*.name, 'Integration')
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/createcandle/candle-controller/projects/3'
        column_name: 'Unassigned'
